theme: jekyll-theme-minimal
title: "MaryAnn Duman's Coding Portfolio"
email: "maryannduman4@gmail.com"
description: "A showcase of my recent coding projects, technical skills, and professional accomplishments."

# Your Personal Bio Info
author:
  name: "MaryAnn Duman"
  bio: "Still learning web development."

# Social Media Links
github_username: "mduman6"